### ISSUE TITLE
Inside caffe2

### ISSUE THREAD

**Issue by seanshpark** [seanshpark/journal#9]
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile

**Comment by seanshpark** [comment]
```
sudo apt-get install libgoogle-glog-dev libgtest-dev libiomp-dev \
      libleveldb-dev liblmdb-dev libopencv-dev libopenmpi-dev \
      libsnappy-dev libprotobuf-dev
```

**Comment by seanshpark** [comment]
```
pip install --user future numpy protobuf typing hypothesis
```

```
sudo apt-get install libgflags-dev cmake
```

**Comment by seanshpark** [comment]
```
git clone https://github.com/pytorch/pytorch.git
```

**Comment by seanshpark** [comment]
```
cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
```

**Comment by seanshpark** [comment]
```
Submodule 'third_party/ComputeLibrary' (https://github.com/ARM-software/ComputeLibrary.git) registered for path 'third_party/ComputeLibrary'
Submodule 'third_party/NNPACK_deps/FP16' (https://github.com/Maratyszcza/FP16.git) registered for path 'third_party/FP16'
Submodule 'third_party/NNPACK_deps/FXdiv' (https://github.com/Maratyszcza/FXdiv.git) registered for path 'third_party/FXdiv'
Submodule 'third_party/NNPACK' (https://github.com/Maratyszcza/NNPACK.git) registered for path 'third_party/NNPACK'
Submodule 'third_party/QNNPACK' (https://github.com/pytorch/QNNPACK) registered for path 'third_party/QNNPACK'
Submodule 'third_party/benchmark' (https://github.com/google/benchmark.git) registered for path 'third_party/benchmark'
Submodule 'third-party/cpuinfo' (https://github.com/Maratyszcza/cpuinfo.git) registered for path 'third_party/cpuinfo'
Submodule 'third_party/cub' (https://github.com/NVlabs/cub.git) registered for path 'third_party/cub'
Submodule 'third_party/eigen' (https://github.com/eigenteam/eigen-git-mirror.git) registered for path 'third_party/eigen'
Submodule 'third_party/fbgemm' (https://github.com/pytorch/fbgemm) registered for path 'third_party/fbgemm'
Submodule 'third_party/gemmlowp/gemmlowp' (https://github.com/google/gemmlowp.git) registered for path 'third_party/gemmlowp/gemmlowp'
Submodule 'third_party/gloo' (https://github.com/facebookincubator/gloo) registered for path 'third_party/gloo'
Submodule 'third_party/googletest' (https://github.com/google/googletest.git) registered for path 'third_party/googletest'
Submodule 'third_party/ideep' (https://github.com/intel/ideep) registered for path 'third_party/ideep'
Submodule 'third_party/ios-cmake' (https://github.com/Yangqing/ios-cmake.git) registered for path 'third_party/ios-cmake'
Submodule 'third_party/nccl/nccl' (https://github.com/NVIDIA/nccl) registered for path 'third_party/nccl/nccl'
Submodule 'third_party/neon2sse' (https://github.com/intel/ARM_NEON_2_x86_SSE.git) registered for path 'third_party/neon2sse'
Submodule 'third_party/onnx' (https://github.com/onnx/onnx.git) registered for path 'third_party/onnx'
Submodule 'third_party/onnx-tensorrt' (https://github.com/onnx/onnx-tensorrt) registered for path 'third_party/onnx-tensorrt'
Submodule 'third_party/protobuf' (https://github.com/google/protobuf.git) registered for path 'third_party/protobuf'
Submodule 'third_party/NNPACK_deps/psimd' (https://github.com/Maratyszcza/psimd.git) registered for path 'third_party/psimd'
Submodule 'third_party/NNPACK_deps/pthreadpool' (https://github.com/Maratyszcza/pthreadpool.git) registered for path 'third_party/pthreadpool'
Submodule 'third_party/pybind11' (https://github.com/pybind/pybind11.git) registered for path 'third_party/pybind11'
Submodule 'third_party/python-enum' (https://github.com/PeachPy/enum34.git) registered for path 'third_party/python-enum'
Submodule 'third_party/python-peachpy' (https://github.com/Maratyszcza/PeachPy.git) registered for path 'third_party/python-peachpy'
Submodule 'third_party/python-six' (https://github.com/benjaminp/six.git) registered for path 'third_party/python-six'
Submodule 'third_party/sleef' (https://github.com/shibatch/sleef) registered for path 'third_party/sleef'
Submodule 'third_party/zstd' (https://github.com/facebook/zstd.git) registered for path 'third_party/zstd'
```

**Comment by seanshpark** [comment]
```
NO_CUDA=1 NO_CUDA=1 NO_MIOPEN=1 NO_MKLDNN=1 NO_NNPACK=1 \
NO_QNNPACK=1 NO_DISTRIBUTED=1 NO_SYSTEM_NCCL=1 NO_TEST=1 \
python setup.py install
```

third_party/sleef/src/libm/CMakeLists.txt
```
#set(EXT_ENABLE_ALIAS AVX512F ADVSIMD NEON32)
set(EXT_ENABLE_ALIAS ADVSIMD NEON32)
```

**Comment by seanshpark** [comment]
Build with x86-64

```
git clone https://github.com/pytorch/pytorch.git
```

```
cd pytorch
git submodule update --init --recursive
python setup.py build
```
Original page says `python setup.py install`, this will try to copy to `/usr/local` which fails.

**Comment by seanshpark** [comment]
```py
from caffe2.python import core
```

```
Traceback (most recent call last):
  File "./test.py", line 1, in <module>
    from caffe2.python import core
  File "/home/maxwell/github/pytorch/pytorch/build/lib.linux-x86_64-2.7/caffe2/python/core.py", line 15, in <module>
    from caffe2.python import scope, utils, workspace
  File "/home/maxwell/github/pytorch/pytorch/build/lib.linux-x86_64-2.7/caffe2/python/workspace.py", line 53, in <module>
    GetCuDNNVersion = C.get_cudnn_version
```

**Comment by seanshpark** [comment]
```
import caffe2.python._import_c_extension as C
```

**Comment by seanshpark** [comment]
`get_cudnn_version` error was from incorrrect cuda path settings
rebuild all with
```
export PATH=$PATH:/usr/local/cuda/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64
```
works ok.
